<?php

namespace Proxies\__CG__\Entities\Finance;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SpendCategory extends \Entities\Finance\SpendCategory implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getSpendcategoryId()
    {
        $this->__load();
        return parent::getSpendcategoryId();
    }

    public function setSpendcategoryName($spendcategoryName)
    {
        $this->__load();
        return parent::setSpendcategoryName($spendcategoryName);
    }

    public function getSpendcategoryName()
    {
        $this->__load();
        return parent::getSpendcategoryName();
    }

    public function setSpendcategoryDesc($spendcategoryDesc)
    {
        $this->__load();
        return parent::setSpendcategoryDesc($spendcategoryDesc);
    }

    public function getSpendcategoryDesc()
    {
        $this->__load();
        return parent::getSpendcategoryDesc();
    }

    public function addMerchantCode(\Entities\Finance\MerchantCode $merchantCodes)
    {
        $this->__load();
        return parent::addMerchantCode($merchantCodes);
    }

    public function getMerchantCodes()
    {
        $this->__load();
        return parent::getMerchantCodes();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'spendcategory_id', 'spendcategory_name', 'spendcategory_desc', 'merchant_codes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}