<?php

namespace Proxies\__CG__\Entities\Finance;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MerchantCode extends \Entities\Finance\MerchantCode implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getMerchantcodeId()
    {
        $this->__load();
        return parent::getMerchantcodeId();
    }

    public function setMerchantcodeCode($merchantcodeCode)
    {
        $this->__load();
        return parent::setMerchantcodeCode($merchantcodeCode);
    }

    public function getMerchantcodeCode()
    {
        $this->__load();
        return parent::getMerchantcodeCode();
    }

    public function setMerchantcodeName($merchantcodeName)
    {
        $this->__load();
        return parent::setMerchantcodeName($merchantcodeName);
    }

    public function getMerchantcodeName()
    {
        $this->__load();
        return parent::getMerchantcodeName();
    }

    public function addPurchase(\Entities\Finance\Purchase $purchases)
    {
        $this->__load();
        return parent::addPurchase($purchases);
    }

    public function getPurchases()
    {
        $this->__load();
        return parent::getPurchases();
    }

    public function setSpendCategory(\Entities\Finance\SpendCategory $spendCategory = NULL)
    {
        $this->__load();
        return parent::setSpendCategory($spendCategory);
    }

    public function getSpendCategory()
    {
        $this->__load();
        return parent::getSpendCategory();
    }

    public function setPlaceType(\Entities\Google\PlaceType $placeType = NULL)
    {
        $this->__load();
        return parent::setPlaceType($placeType);
    }

    public function getPlaceType()
    {
        $this->__load();
        return parent::getPlaceType();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'merchantcode_id', 'merchantcode_code', 'merchantcode_name', 'purchases', 'spend_category', 'place_type');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}