<?php

namespace Proxies\__CG__\Entities\Finance;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Purchase extends \Entities\Finance\Purchase implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPurchaseId()
    {
        $this->__load();
        return parent::getPurchaseId();
    }

    public function setPurchaseTotal($purchaseTotal)
    {
        $this->__load();
        return parent::setPurchaseTotal($purchaseTotal);
    }

    public function getPurchaseTotal()
    {
        $this->__load();
        return parent::getPurchaseTotal();
    }

    public function setPurchaseMerchantname($purchaseMerchantname)
    {
        $this->__load();
        return parent::setPurchaseMerchantname($purchaseMerchantname);
    }

    public function getPurchaseMerchantname()
    {
        $this->__load();
        return parent::getPurchaseMerchantname();
    }

    public function setPurchasePoints($purchasePoints)
    {
        $this->__load();
        return parent::setPurchasePoints($purchasePoints);
    }

    public function getPurchasePoints()
    {
        $this->__load();
        return parent::getPurchasePoints();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setModifiedAt($modifiedAt)
    {
        $this->__load();
        return parent::setModifiedAt($modifiedAt);
    }

    public function getModifiedAt()
    {
        $this->__load();
        return parent::getModifiedAt();
    }

    public function setCard(\Entities\Wallet\Card $card = NULL)
    {
        $this->__load();
        return parent::setCard($card);
    }

    public function getCard()
    {
        $this->__load();
        return parent::getCard();
    }

    public function setMerchantCode(\Entities\Finance\MerchantCode $merchantCode = NULL)
    {
        $this->__load();
        return parent::setMerchantCode($merchantCode);
    }

    public function getMerchantCode()
    {
        $this->__load();
        return parent::getMerchantCode();
    }

    public function setUser(\Entities\User\User $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setCreatedBy(\Entities\User\User $createdBy = NULL)
    {
        $this->__load();
        return parent::setCreatedBy($createdBy);
    }

    public function getCreatedBy()
    {
        $this->__load();
        return parent::getCreatedBy();
    }

    public function setModifiedBy(\Entities\User\User $modifiedBy = NULL)
    {
        $this->__load();
        return parent::setModifiedBy($modifiedBy);
    }

    public function getModifiedBy()
    {
        $this->__load();
        return parent::getModifiedBy();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'purchase_id', 'purchase_total', 'purchase_merchantname', 'purchase_points', 'created_at', 'modified_at', 'card', 'merchant_code', 'user', 'created_by', 'modified_by');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}